all:

clk:
	cp -a clocks_e18c21.dat clocks_e18c21.b4.dat
	cp -a clocks_e18e22.dat clocks_e18e22.b4.dat
	cp -a clocks_e18a24.dat clocks_e18a24.b4.dat
	cp -a clocks_e18c25.dat clocks_e18c25.b4.dat
	cp -a clocks_e18g27.dat clocks_e18g27.b4.dat
	cp -a clocks_e18d28.dat clocks_e18d28.b4.dat
