include ../Makefile.inc

all:

fdistB4:
	cp -a *filelist* /Exps/e18e22/band4/$(REV)
	cp -a *filelist* /Exps/e18c21/band4/$(REV)
	cp -a *filelist* /Exps/e18a24/band4/$(REV)
	cp -a *filelist* /Exps/e18c25/band4/$(REV)
	cp -a *filelist* /Exps/e18g27/band4/$(REV)
	cp -a *filelist* /Exps/e18d28/band4/$(REV)

fdistB1:
	cp -a *filelist* /Exps/e18e22/band1/$(REV)
	cp -a *filelist* /Exps/e18c21/band1/$(REV)
	cp -a *filelist* /Exps/e18a24/band1/$(REV)
	cp -a *filelist* /Exps/e18c25/band1/$(REV)
	cp -a *filelist* /Exps/e18g27/band1/$(REV)
	cp -a *filelist* /Exps/e18d28/band1/$(REV)
