
all:

clk:
	cp -a clocks_e18c21.dat clocks_e18c21.b1.dat
	cp -a clocks_e18e22.dat clocks_e18e22.b1.dat
	cp -a clocks_e18a24.dat clocks_e18a24.b1.dat
	cp -a clocks_e18c25.dat clocks_e18c25.b1.dat
	cp -a clocks_e18g27.dat clocks_e18g27.b1.dat
	cp -a clocks_e18d28.dat clocks_e18d28.b1.dat

